### ISSUE TITLE
Unknown prop `componentClass` on <div> tag

### ISSUE THREAD

**Issue by alexandru-tomescu** [bigdatr/react-bouncefix#6]
Warning: Unknown prop `componentClass` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Bouncefix)
    in Bouncefix (created by App)

Thank you

**Comment by wuzhuzhu** [comment]
+1

**Comment by idwebmx** [comment]
Help for warning :(
Warning: Unknown prop componentClass on <div> tag

**Comment by macrozone** [comment]
its fixed in code, but not released.

in your package.json:

```
  "react-bouncefix":
      "https://github.com/bigdatr/react-bouncefix#137d589f61913f98529cb70f0b9ec40e4c9534f0",
```

and npm install / yarn install after that

**Comment by alexandru-tomescu** [comment]
Thanks. Have a good day :)
